Rework get_fw_loc
Fixes raspberrypi/linux#6315

diff --git a/usr/lib/raspberrypi-sys-mods/get_fw_loc b/usr/lib/raspberrypi-sys-mods/get_fw_loc
--- a/usr/lib/raspberrypi-sys-mods/get_fw_loc
+++ b/usr/lib/raspberrypi-sys-mods/get_fw_loc
@@ -5,14 +5,22 @@ if [ -r /etc/default/raspberrypi-sys-mods ]; then
 fi
 
 if [ -z "$FWLOC" ]; then
-  if dpkg --print-architecture | grep -q '^arm'; then
-    for FWLOC in /boot /boot/firmware NOT_FOUND; do
-      if ( findmnt --fstab "$FWLOC" || findmnt "$FWLOC" ) > /dev/null; then
-        break
+  if ! dpkg --print-architecture | grep -q '^arm'; then
+    FWLOC=/boot
+    break
+  fi
+  for FWLOC in /boot/firmware /boot NOT_FOUND; do
+    if ( findmnt --fstab "$FWLOC" || findmnt "$FWLOC" ) > /dev/null; then
+      break
+    fi
+  done
+  if [ "$FWLOC" = "NOT_FOUND" ]; then
+    echo "WARNING: Firmware partition not found, searching for config.txt.."  >$2
+    for FWLOC in /boot/firmware /boot NOT_FOUND; do
+      if [ -f "$FWLOC/config.txt" ]; then
+	break
       fi
     done
-  else
-    FWLOC=/boot
   fi
 fi
 
